### ISSUE TITLE
How to play meerkat live streams on web?

### ISSUE THREAD

**Issue by mingji** [appmeerkat/meerkat-api#13]
Hi,
I  have succeed to get all broadcasts and get each broadcast 's summary information such as cover image url, profile image url, display name, watcher count, liker count...
Now I 'm trying to play the each live streams in web browser.
How can I embed the video player and set the url of live stream?

**Comment by isabo** [comment]
Are you talking about this? http://meerkatapp.co/embed 
More details: http://developers.meerkatapp.co/embed/

**Comment by mingji** [comment]
Can I play meerkat video stream outside of meerkat?
Now I 'm trying to play it on our own website.

**Comment by ciaranschutte** [comment]
I think a Meerkat stream is a HLS stream. So you can get the playlist file http://cdn.meerkatapp.co/broadcast/{broadcast}/live.m3u8

**Comment by mingji** [comment]
Thanks.
I have succeed to get play list file and downloaded ts files to my local server.
When we are playing them on our server, there is no problem to play that stream.
By the way, can not we play live stream on meerkat server directly?

If change the ts file path such as http://cdn.meerkatapp.co/broadcast/d1941995-6f8b-4a09-ac74-d53b42dca1a4/chunk_0007315.ts, there is some error <...not allowed access >.

ex: live.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:4
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:7240
#EXTINF:3.743
http://cdn.meerkatapp.co/broadcast/d1941995-6f8b-4a09-ac74-d53b42dca1a4/chunk_0007315.ts
#EXTINF:3.743
http://cdn.meerkatapp.co/broadcast/d1941995-6f8b-4a09-ac74-d53b42dca1a4/chunk_0007330.ts
#EXTINF:3.743
http://cdn.meerkatapp.co/broadcast/d1941995-6f8b-4a09-ac74-d53b42dca1a4/chunk_0007332.ts

How can we play live stream meerkat server directly?

**Comment by appmeerkat** [comment]
In order to preserve the interactivity and full-featured meerkat experience, we encourage you to use our embeddable player (details at meerkatapp.co/embed) 

Is there something in particular preventing you from using the embed?  All feedback is welcome!
