### ISSUE TITLE
How to broadcast using the API?

### ISSUE THREAD

**Issue by bobbyware** [appmeerkat/meerkat-api#14]
As far as I can tell are all the API endpoints only for retrieving broadcasts, not for sending a broadcast. Is this true? Any plans to make broadcasting using the API possible?

**Comment by p1nox** [comment]
+1

**Comment by CarePlanners** [comment]
+1

**Comment by CarePlanners** [comment]
+1

**Comment by appmeerkat** [comment]
Thanks for the feedback! 

At this time the API is read-only, and broadcasts must originate from either the iOS or Android Meerkat app.

We'll be sure to let all our devs know if/when this changes. 

Thanks! 😃
