### ISSUE TITLE
Haven't received API token after several days

### ISSUE THREAD

**Issue by mitch-seymour** [appmeerkat/meerkat-api#15]
I applied for an API token about a week ago but haven't received it yet. Could one of you meerkats please check on this? :) Can't wait to explore the API!

**Comment by bobbyware** [comment]
Multiple reports about this, I'm waiting for a week as well. Seems that the owner has less time / gives this a lower priority / ...

**Comment by mitch-seymour** [comment]
Just got my API token :) Thanks guys
