### ISSUE TITLE
GPS function on Meerkat

### ISSUE THREAD

**Issue by mstan002** [appmeerkat/meerkat-api#17]
A GPS location feature is absolutely essential for competing with Periscope.  Is this in the works?

**Comment by appmeerkat** [comment]
Hi there,

We'd love to hear your feedback regarding what you mean by "GPS location"  -- we allow broadcasters to share their general location, and there have been some cool 3rd party solutions built to surface this info -- check out http://map.meerkat.ovh

Thanks! 😃

**Comment by mstan002** [comment]
By "GPS location," I mean a feature where you can locate current users
live-broadcasting based on their geographic location.  Periscope uses a map
feature which shows where broadcasts are originating.
