### ISSUE TITLE
My idea and suggestion

### ISSUE THREAD

**Issue by luisenrique35** [appmeerkat/meerkat-api#18]
Congratulations , excellent application. I have an idea for you.

It can be integrated with Merkaat MAKE.TV . The idea is that a TV channel can receive the transmission of all its users .

My idea is that this would be useful for the group function . So everyone in a group can be transmitted if the administrator allows .

Multiple users transmit to a single account . This is possible?

**Comment by appmeerkat** [comment]
You can share twitter credentials.  The app allows a user's account to be logged in on multiple devices.  It is best to coordinate though, so multiple streams aren't being streamed from the same account at the same time.

Hope this helps! 😃

**Comment by luisenrique35** [comment]
I wanted to create a network of reporters. to transmit all to the same
account. :(

2015-08-14 22:46 GMT-04:30 appmeerkat notifications@github.com:

> You can share twitter credentials. The app allows a user's account to be
> logged in on multiple devices. It is best to coordinate though, so multiple
> streams aren't being streamed from the same account at the same time.
> 
> Hope this helps! 😃
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/appmeerkat/meerkat-api/issues/18#issuecomment-131286411
> .

## 

Luis De Gouveia

Twitter: @luisdgouveia https://twitter.com/LuisDGOUVEIA

Móvil: +584141349871
