### ISSUE TITLE
Haven't received API key

### ISSUE THREAD

**Issue by dray92** [appmeerkat/meerkat-api#6]
I submitted the API token application form. Never received an email confirmation or any other email communication from Meerkat

**Comment by appmeerkat** [comment]
Hi Dray,

Sorry for the delay.  You will be receiving your token soon.

Thanks! :smile:

**Comment by mingji** [comment]
Hi,
I 'v also applied for an api token 2 days ago, but not received an email confirmation from Meerkat.

**Comment by dray92** [comment]
Hi there,

I still haven't received the token. Just wanted to check back. :)
- debo

On Wed, Jul 22, 2015 at 1:54 PM, appmeerkat notifications@github.com
wrote:

> Hi Dray,
> 
> Sorry for the delay. You will be receiving your token soon.
> 
> Thanks! [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/appmeerkat/meerkat-api/issues/6#issuecomment-123859783
> .

## 

Debosmit Ray
Electrical Engineering, Computer Science | _University of Washington_ (2015)
_B. S._ Bachelor of Science | _Embedded Systems_
Secretary | _UW IEEE-HKN_
Member | _Senior Class Gift Council_
Data Ninja | _uReporter_
_S2SS_ | _Edify_

dray92@uw.edu | +1 (206) 495 2689

**Comment by bobbyware** [comment]
Do you have your API key yet?

I'm planning to build an app using the API, but I see a lot of topics here unanswered. There are some topics where Meerkat should act, but does not do. I'm reluctant to put my effort in the API when the owners don't care about it...

**Comment by mingji** [comment]
I have not received my api token yet. Should I re-signup account?
