### ISSUE TITLE
Get routes

### ISSUE THREAD

**Issue by nomorequestion** [appmeerkat/meerkat-api#7]
While 

........ GET https://resources.meerkatapp.co/broadcasts

works like a charm (I am using Java Jersey RESTful Web Services, but this shouldn't be relevant here), the service 

........ GET https://api.meerkatapp.co/routes

doesn't work. It is keeping asking me to provide the version parameter v in the request, even if I do provide it - exactly as when I get the broadcasts: webResource.property("v", "1.0"); 

{"error":"Version check Failed, missing parameter 'v' in request"}.

Any idea?

Thanks for your help :-)

**Comment by appmeerkat** [comment]
Looks like you might be missing the version parameter in the query string for routes... have you tried https://api.meerkatapp.co/routes?v=1.0
:smile:

**Comment by nomorequestion** [comment]
Thanks, this works if I write this directly in the URL.

**Comment by BailangCKK** [comment]
I can not use Api.
Please help me.

Thank you.
